import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Planets from "./planets";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          {/*<Planets />*/}
          <Link href="./planets">
            <h1>Planets</h1>
          </Link>
          <Link href="./animals">
            <h1>Animals</h1>
          </Link>
          <Link href="./dogs">
            <h1>Dogs</h1>
          </Link>
          <Link href="./music">
            <h1>Music</h1>
          </Link>
        </div>
      </main>
    </>
  );
}
